### PR TITLE
Finer Time Granularity

### LINKED ISSUE #27: Refine Time Granularity to Seconds
Makes for smoother animation.

### PR DESCRIPTION
**Pull request by LeoWoerteler**
Fixes #27.

The _now_ view is currently very CPU intensive, as it's updated every second. Ideas?

### CODE REVIEW

**Comment by JosuaKrause** [comment]
The now view only updates the routing every minute. It just updates the label every second. Have you measured the cpu usage? Seems like you have to adapt your pull request to integrate the fast-forward mode - sorry one hour too late :P

**Comment by LeoWoerteler** [comment]
I changed the update rate to once per second to show the difference the higher time resolution makes. Something in between would probably make more sense.

**Comment by JosuaKrause** [comment]
Do the seconds have influence in routing?

**Comment by LeoWoerteler** [comment]
Yes, because the walking edges have sub-minute precision.

**Comment by JosuaKrause** [comment]
Ok, back from lunch - start merging. Wish me luck :)

**Pull request merged**
